services:
  db:
    image: postgres:latest
    container_name: property-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
  caching:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379

